<!-- stylesheets -->
<%@include file="style.inc" %>
<!-- scripts (jquery) -->
<script src="${ctx}/static/frame/common.js"></script>
<script src="${ctx}/static/frame/jquery-1.11.2.min.js"></script>


<!-- scripts (pagewalkthrough) -->
<script src="${ctx }/static/frame/pagewalkthrough/jquery.pagewalkthrough.js"></script>
<!--[if It IE 8]>
<script type="text/javascript" src="${ctx }/static/frame/jquery.placeholder.min.js"></script>

<!-- scripts (bootstrap) -->
<script src="${ctx }/static/frame/bootstrap-3.3.4/js/bootstrap.min.js"></script>
<script src="${ctx }/static/frame/style/common.js"></script>
<script src="${ctx }/static/frame/style/banner.js"></script>

<!-- scripts (other) -->
<script src="${ctx }/static/frame/sockjs.min.js"></script>
<script src="${ctx }/static/frame/common.js"></script>
<script src="${ctx }/static/frame/page$.js"></script>
<script src="${ctx }/static/frame/page.js"></script>
<script src="${ctx }/static/frame/pagediv.js"></script>
<script src="${ctx }/static/frame/sort.js"></script>